# Generated by Django 6.0.6 on 2026-07-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='entry_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
