# Generated by Django 6.0.6 on 2026-07-12 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('person', '0002_customer_balance_employee_balance'),
        ('sale', '0003_alter_saleorder_sold_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='person.customer')),
                ('reference_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.payment')),
                ('reference_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.saleorder')),
            ],
            options={
                'ordering': ['transaction_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('reference_sale__isnull', False)), fields=('customer', 'reference_sale'), name='unique_sale_ledger'), models.UniqueConstraint(condition=models.Q(('reference_payment__isnull', False)), fields=('customer', 'reference_payment'), name='unique_payment_ledger')],
            },
        ),
    ]
