# Generated by Django 6.0.6 on 2026-07-22 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_weight'),
        ('purchase', '0002_alter_purchaseorder_entry_by'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Per-unit purchase price for this batch', max_digits=12)),
                ('quantity', models.PositiveIntegerField(help_text='Remaining quantity in this batch')),
                ('original_quantity', models.PositiveIntegerField(help_text='Quantity this batch started with')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='products.product')),
                ('purchase_item', models.ForeignKey(blank=True, help_text='Originating purchase line, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='purchase.purchaseitem')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.stock')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='stock_stock_product_6a3929_idx')],
            },
        ),
    ]
