# Generated by Django 6.0.6 on 2026-07-22 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftSale', '0003_alter_draftsaleorder_sold_by'),
        ('stock', '0002_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsaleitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Batch the user selected at draft time (not consumed; informational only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_sale_items', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='draftsaleitem',
            name='unit_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
