# Generated by Django 6.0.6 on 2026-07-18 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftPurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('entry_by', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='DraftPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost_bdt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost_bdt', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
                ('draft_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='draftPurchase.draftpurchaseorder')),
            ],
        ),
    ]
