# Generated by Django 6.0.6 on 2026-07-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draftPurchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftpurchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='draftpurchaseitem',
            name='duty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
