# Generated by Django 6.0.6 on 2026-07-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Multiplier used to calculate sale price from purchase price', max_digits=10, null=True),
        ),
    ]
