# Generated by Django 6.0.6 on 2026-07-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_saleitem_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleorder',
            name='sold_by',
            field=models.CharField(blank=True, help_text='Name of the person who made the sale', max_length=100, null=True),
        ),
    ]
