# Generated by Django 6.0.6 on 2026-07-22 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_alter_saleorder_sold_by'),
        ('stock', '0002_stockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='The specific stock batch this line consumed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='stock.stockbatch'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
