# Generated by Django 6.0.6 on 2026-07-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='EAN-13 or custom barcode', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, help_text='Category > Sub-Category hierarchy', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='markup_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Markup % on INR (for imports)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock_level',
            field=models.IntegerField(blank=True, default=5, help_text='Reorder alert threshold per warehouse', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='mrp_inr',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Maximum Retail Price in Indian Rupee', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated system ID', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, help_text='Full descriptive name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Discontinued', 'Discontinued'), ('Seasonal', 'Seasonal'), ('Damaged', 'Damaged (slow-moving)')], default='Active', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.IntegerField(blank=True, default=5, help_text='Trigger for purchase requisition', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='retail_price_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Selling price for retail customers', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, choices=[('Import', 'Import (India)'), ('Local', 'Local Purchase')], default='Local', help_text='Determines pricing rules', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='piece', help_text='Primary unit (piece, set, box)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_code',
            field=models.CharField(blank=True, help_text='Applicable VAT rate code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_period',
            field=models.IntegerField(blank=True, default=0, help_text='Warranty period in months', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_price_bdt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Selling price for wholesale dealers', max_digits=10, null=True),
        ),
    ]
