# Generated by Django 6.0.6 on 2026-07-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='handled_by',
            field=models.CharField(blank=True, help_text='Name of the person who made the payment', max_length=100, null=True),
        ),
    ]
